name: Docker dev workflow

on:
  push:
    branches: [aula-3]
  pull_request:
    branches: [aula-3]

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout do código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker compose
        run: |
          if ! command -v docker-compose &> /dev/null
          then
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
          fi

      - name: Mascarar variáveis de ambiente sensíveis
        run: |
          echo "::add-mask::${{ secrets.MONGO_URI }}"

      - name: Cria .env para todos os serviços
        working-directory: burguer-app
        run: |
          for service in auth-service user-service order-service product-service; do
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > $service/.env
          done

      - name: Versionamento
        id: server
        run: |
          VERSION=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV

      - name: Docker compose up
        working-directory: burguer-app
        run: |

          docker-compose -f docker-compose.yml -f docker-compose.override.yml down
          for service in auth-service user-service order-service product-service; do
            docker build -t burguer-app-${service}:${{ env.IMAGE_TAG }} ./$service
            docker tag burguer-app-${service}:${{ env.IMAGE_TAG }} burguer-app-${service}:latest
          done
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build

      - name: Wainting for mongo to be ready
        run: |
          sleep 20

      - name: Test auth-service
        working-directory: burguer-app/auth-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -v

      - name: Test user-service
        working-directory: burguer-app/user-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -v

      - name: Test order-service
        working-directory: burguer-app/order-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -v

      - name: Test product-service
        working-directory: burguer-app/product-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -v

      - name: Shut down Docker conteiners
        working-directory: burguer-app
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml down

      - name: Verificar vulnerabilidades nas imagens com trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

      - name: Verificar vulnerabilidade da imagem auth-service
        working-directory: burguer-app/auth-service
        run: |
          trivy image --severity HIGH --severity CRITICAL burguer-app-auth-service:latest

      - name: Verificar vulnerabilidade da imagem user-service
        working-directory: burguer-app/user-service
        run: |
          trivy image --severity HIGH --severity CRITICAL burguer-app-user-service:latest

      - name: Verificar vulnerabilidade da imagem order-service
        working-directory: burguer-app/order-service
        run: |
          trivy image --severity HIGH --severity CRITICAL burguer-app-order-service:latest

      - name: Verificar vulnerabilidade da imagem product-service
        working-directory: burguer-app/product-service
        run: |
          trivy image --severity HIGH --severity CRITICAL burguer-app-product-service:latest

      - name: Roolback
        if: failure()
        working-directory: burguer-app
        run: |
          echo "Roolback automatico: usado as imagens anteriores"
          for service in auth-service user-service order-service product-service; do
            PREV_TAG=$(docker images burguer-app-${service} --format "{{.Tag}}" | grep -v latest | head -n 2)
            if [ -z "$PREV_TAG"]; then
              echo "Nenhuma imagem anteriores encontrada para $service"
            else
              docker tag burguer-app-${service}:${PREV_TAG} burguer-app-${service}:latest
              echo "Imagem anteriores para $service: $PREV_TAG"
            fi
          done

          docker-compose -f docker-compose.yml -f docker-compose.override.yml down

          for service in auth-service user-service order-service product-service; do
            docker build -t burguer-app-${service}:${{ env.IMAGE_TAG }} ./$service
            docker tag burguer-app-${service}:${{ env.IMAGE_TAG }} burguer-app-${service}:latest
          done
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build
