name: Docker dev workflow

on:
  push:
    branches: [aula-3]
  pull_request:
    branches: [aula-3]

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout do código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Cria .env para todos os serviços
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > user-service/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > auth-service/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > order-service/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > product-service/.env

      - name: Docker compose up
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml down
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up

      - name: Wainting for mongo to be ready
        run: |
          sleep 20

      - name: Shut down Docker conteiners
        working-directory: burguer-app
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml down
